services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    # memory 2g
    shm_size: 2g
  fibre_web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - selenium
    environment:
      SELENIUM_HUB_URL: http://selenium:4444/wd/hub