apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibre-from-address
  labels:
    app: fibre-from-address
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibre-from-address
  template:
    metadata:
      labels:
        app: fibre-from-address
    spec:
      containers:
      - name: fibre-from-address
        image: harbor.k8s.local/fibre_from_address/fibre_from_address:0.2.0
        ports:
        - containerPort: 5000
        env:
        - name: SELENIUM_REMOTE_URL
          value: "http://selenium:4444/wd/hub"
        resources:
          limits:
            cpu: 2
            memory: 4096Mi
          requests:
            cpu: 1
            memory: 2048Mi
